name: ecoroute
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  country_picker: ^2.0.21
    
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.5.0
  image_picker: ^1.1.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0 
  google_maps_flutter: ^2.6.0   
  geolocator: ^13.0.1
  shared_preferences: ^2.5.2
  http: ^1.4.0
  flutter_secure_storage: ^9.2.4
  uuid: ^4.5.1
  fluttertoast: ^8.2.4
  cached_network_image: ^3.2.3
  intl: ^0.18.1
  permission_handler: ^11.3.0
  flutter_polyline_points: ^3.0.1 
  url_launcher: ^6.3.0
  geocoding: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: BricolageGrotesque
      fonts:
        - asset: assets/fonts/BricolageGrotesque-Regular.ttf

